Kamon 2.0
kamon-io/kamon-cassandra pull request #6
Opened 2019-11-07 07:28 UTC by mladens

Bumps Kamon to 2.0, introduces tracing for each internal query execution (fetches, speculative executions, retries), metrics for errors and timeouts on execution level. 

Server instrumentation removed, to be moved to separate repo

2019-11-25 06:44 UTC, ivantopo requested changes

2019-11-25 06:44 UTC, ivantopo commented on build.sbt
> +val kamonTestkit        = "io.kamon"            %% "kamon-testkit"            % "2.0.0-M4"
Please use the latest core, testkit and kanela versions.

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ConnectionPoolAdvice.scala
> +        ClientMetrics.poolBorrow(target).record(duration(time))
Instead of looking up the metrics every time, why not mix in the appropriate metric group into the `HostConnectionPool` and just retrieve it from there?

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutionAdvices.scala
> +      .withEntry(ParentSpanKey, clientSpan)
What is the logic behind storing both the client Span and the parent Span?

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutionAdvices.scala
> +    Kamon.storeContext(Context.of(Span.Key, clientSpan))
Here this shouldn't be creating a new Context that just has the Span but rather use the original Context with the new Span entry. That's in case that there is additional information in the Context that might be useful for the user.

Also, where is the Context stored by this action being cleaned up? :thinking:

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutionAdvices.scala
> +    executionSpan.tagMetrics("target", TargetResolver.getTarget(host.getAddress))
There should be an option to decide whether to tag by `target` or not because depending on the deployment size this could introduce a cardinality problem. Let's do something similar to what we do in the [common HTTP instrumentation](https://github.com/kamon-io/kamon-instrumentation-common/blob/master/src/main/resources/reference.conf#L73-L95): add a setting to decide what kind of tag it will be and by default only add the dc and rack to the span metric tags and leave target as a span tag only.

Also, please add a `cassandra` prefix to those tags.

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutionAdvices.scala
> +    executionSpan.mark("writing")
Please change to a more descriptive name. Something like `cassandra.connection.write-started` (or similar that makes sense).

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutorQueueMetricsExtractor.scala
> +object ExecutorQueueMetricsExtractor {
Instead of just getting queue size, what about instrumenting the methods that create those pools on `com.datastax.driver.core.ThreadingOptions` to use the kamon-executors' instrumentation and get the entire set of metrics for them?

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/ClientMetrics.scala
> +object ClientMetrics {
For all the metrics that will remain, separate the metric definition from the actual lookup. A pattern that we have been following on other modules is to define the metrics in a val, including a description of the metric (that ends up in the status page, Prometheus and so on) and then have instrument groups when more than one instrument is associated with the same logical entity. 

Besides the above, unless there is absolutely no other way to do it, please use instrument groups and mix them into the monitored entities instead of looking them up every time they are needed.

Here is an example from the Akka instrumentation that can help: https://github.com/kamon-io/kamon-akka/blob/master/instrumentation/common/src/main/scala/kamon/instrumentation/akka/AkkaMetrics.scala

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/ClientMetrics.scala
> +    Kamon.histogram("cassandra.trashed-connections").withTag("target", host)
Could this be a counter and incremented when HostConnectionPool trashes a connection?

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/ClientMetrics.scala
> +    Kamon.histogram("cassandra.connection-pool.size").withTag("target", host)
Could this be a range sampler instead and capture it from the HostConnectionPool? Also.. given the super high limits on the protocol V3 it looks like the value will almost always be 1, would it be possible to have a separate metric with the total number of connections across all hosts?

2019-11-25 06:44 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/ClientMetrics.scala
> +    Kamon.scheduler().scheduleAtFixedRate(new Runnable {
I'm almost sure that we can get rid of this scheduling, but let's get back to it after all other changes are applied.

2019-11-26 10:08 UTC, liff commented on README.md
> +- `cassandra.keyspace`
Would you perhaps be willing to consider #2 ?

2019-11-26 18:34 UTC, mladens commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutionAdvices.scala
> +      .withEntry(ParentSpanKey, clientSpan)
Execution span is required for tagging and measuring execution itself. After execution is done and `fetchMore` invoked by exhausting result set iterator, we want fetch execution span to be a sibling of original one, hence carrying around the parent too.

2019-11-26 18:35 UTC, mladens commented on README.md
> +- `cassandra.keyspace`
Done, thanks for bringing it up!

2019-11-30 11:15 UTC, mladens commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/ClientMetrics.scala
> +    Kamon.histogram("cassandra.connection-pool.size").withTag("target", host)
Moved it to HostConnectionPool, total number of connections across all host would be just this metric aggregated across all of them, or is there a specific reason for a separate metric?

2019-12-02 16:23 UTC, ivantopo requested changes

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/KamonSession.scala
> +  def getQuery(statement: Statement): String = statement match {
This should also handle `com.datastax.driver.core.BatchStatement` and have a default case so it wont explode for some other unknown implementations of `Statement`.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/KamonSession.scala
> +class KamonSession(underlying: Session) extends AbstractSession {
Please, call this something like `InstrumentedSession`.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/PoolMetrics.scala
> +class PoolMetrics(node: TargetNode) {
This should be a `MetricGroup`. Following the same theme from other instrumentations, this should be be an inner class on the `PoolMetrics` object called `PoolInstruments`.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/PoolMetrics.scala
> +    "cassandra.client.pool.borrow-time",
Please add the explicit parameter names here, like `name = ..... ` and `description = .... `

2019-12-02 16:23 UTC, ivantopo commented on build.sbt
> +val kamonTestkit        = "io.kamon"            %% "kamon-testkit"            % "2.0.0-M4"
The testkit version should be the same as core.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/Cassandra.scala
> +  case class ClientInstrumentationConfig(samplingIntervalMillis: Long, nodeTags: NodeTags)
`samplingIntervalMillis` is not being used anymore, please remove it. Also, please change `Cassandra` to `CassandraInstrumentation` and `ClientInstrumentationConfig` to simple `Settings`. That's to follow the same patterns we have in other modules.

You might as well need "inline" the `NodeTags` class since it will be the only member in there so far.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/QueryMetrics.scala
> +object QueryMetrics {
Same comments as in `PoolMetrics`.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ConnectionPoolAdvices.scala
> +        metrics.inflightPerConnection.record(borrowedConnection.inFlight.get)
Is it possible for `inflightPerConnection` and `inflightPerHost` to become range samplers instead of histograms?

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutionAdvices.scala
> +    metrics.tagSpan(executionSpan)
This second call is not necessary, there is no need to repeat the metric tags as span tags as well.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ExecutionAdvices.scala
> +    executionSpan.trackMetrics()
Why is this call here? Even if this needs to be here, any calls made after finishing a Span are noop. Also, try using the fluent APIs on spans when doing several actions on the same Span.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/resources/reference.conf
> +      tag {
Let's move this to follow the same conventions we have in the HTTP instrumentation: users should be able to select between `span`, `metric` and `off` for each of these tags. Take a look at [this example config](https://github.com/kamon-io/kamon-instrumentation-common/blob/master/src/main/resources/reference.conf#L68-L95).

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/resources/reference.conf
>        bundle-name = "DataStax Java Driver for Apache Cassandra - Core"
- Remove `bundle-name`
- change the name to `cassandra-client`
- remove the `show-banner` and `log-level` settings from the Kanela section

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/resources/reference.conf
>      sample-interval = 100 milliseconds
Remove this setting since it is no longer used.

2019-12-02 16:23 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/executors/ExecutorInstrumentation.scala
> +  val componentTags = TagSet.of("component", "cassandra-client")
Call it `cassandra.client`

2019-12-02 17:50 UTC, mladens commented on build.sbt
> +val kamonTestkit        = "io.kamon"            %% "kamon-testkit"            % "2.0.0-M4"
`2.0.2` testkit has not been released

2019-12-05 14:08 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/client/ClientMetrics.scala
> +    Kamon.histogram("cassandra.connection-pool.size").withTag("target", host)
The metrics would have a different behavior. For example, if you have 10 cassandra nodes and 1 connection to each one of them then:
  - The per-host range sampler will always be recording the value 1. Aggregating the 10 individual range samplers together will still produce a value of 1. If some connections come and go, the value will always be between 0 and 1.
  - The global connections range sampler will be around 10 when all connections are open. If some connections come and go the value will always be between 0 and 10. 

Does this make the difference more clear why a separate range sampler for all connections would be useful? :thinking:

2019-12-05 14:09 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/Cassandra.scala
> +  case class ClientInstrumentationConfig(samplingIntervalMillis: Long, nodeTags: NodeTags)
Ping on this (changing it to `Settings`).

2019-12-12 09:51 UTC, ivantopo commented
Hey @mladens, I was testing this in tiny app and found a few issues by examining the data on both the Status Page and some of the data that came to Kamon APM. Here is the summary of my findings:

- [ ]  We should add the "cluster" tag to everything related to the same Cluster. The cluster name setting can be added when creating a Client Cluster although it does not have anything to do with the actual cassandra cluster name. It is specially important if a single app is connecting to more than one Cassandra cluster
- [ ]  Missing instrumentation description for the Status Page. Just include a description on the `reference.conf` file.
- [ ]  These metrics do not have any tags:
    - [ ]  cassandra.query.speculative
    - [ ]  cassandra.query.retries
- [ ]  These metrics have an "unknown" value on the `cassandra.dc` tag:
    - [ ]  cassandra.query.errors
    - [ ]  cassandra.query.timeouts
- [ ]  The cassandra.client.pool.size metric has two instances, one without any tags and one with the cassandra.dc tag, why is that?
- [ ]  Should we actually have a cassandra.query.errors metric? isn't it the same as looking at the aggregate of all span.processing-time from cassandra with error=true? I sort of see how this can be a quick go to metric for cassandra-related errors. In that case, what tags will be applied to this tag? 
- [ ]  cassandra.client.inflight-per-target should probably be called cassandra.client.pool.target.in-flight.
- [ ]  cassandra.client.pool.inflight-per-connection should probably be cassandra.client.pool.connection.in-flight.
- [ ]  The cassandra.[dc|rack|node] are missing from Spans. This is weird because I already saw these tags in our traces with a previous version of the instrumentation!
- [ ]  It would be nice if all implementation Spans (like retries and executions) could be turned on or off via config. This is a nice to have thing, if there is no clear/quick way of implementing it right now lets create an issue and tackle this on the next version.

2019-12-16 11:00 UTC, mladens commented
> * [ ]   These metrics do not have any tags:
>   
>   * [ ]   cassandra.query.speculative
>   * [ ]   cassandra.query.retries

Those dont have any sensible dimensions to them,   
     - host that triggered retry - this is already covered by latency and error metrics
     - host that it got retried on, has nothing to do with him
     - similar line of reasoning goes for speculatives
 

> * [ ]   The cassandra.client.pool.size metric has two instances, one without any tags and one with the cassandra.dc tag, why is that?

Metrics are created per target host (depending on config) and one without tags to represent global count across all entire cluster (as requested in one of previous comments)

> * [ ]   Should we actually have a cassandra.query.errors metric? isn't it the same as looking at the aggregate of all span.processing-time from cassandra with error=true? I sort of see how this can be a quick go to metric for cassandra-related errors. In that case, what tags will be applied to this tag?

Could go both ways, I agree that it is a bit redundant. Not sure what is a kamon-wide policy here but i opted for having extra metrics on account of having metrics more understandable and easier to discover/document. Am open to revisiting this decision.


> * [ ]   It would be nice if all implementation Spans (like retries and executions) could be turned on or off via config. This is a nice to have thing, if there is no clear/quick way of implementing it right now lets create an issue and tackle this on the next version.

Not a quick fix im afraid :/ Problem is mostly in transfering execution tags (target..etc) from per-execution span into one client span that could cover multiple executions (multiple hosts, retries, fetches...etc)

2019-12-18 08:27 UTC, ivantopo requested changes
Hey @mladens, I replied to your comments on the code itself so we can keep independent discussions on each of the things that need work.

Regarding other general stuff:
  - Keeping `cassandra.query.errors`. Yes, we keep it.
  - Toggling implementation spans? Future version.
  - Sorry about the corrections on the connection pool metrics. I'm still reasoning about the whole pool of pools thing and want to make sure we will nail this thing.

2019-12-18 08:27 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/PoolMetrics.scala
> +  val PoolBorrowTime        = Kamon.histogram(
This one should be a timer.

2019-12-18 08:27 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/PoolMetrics.scala
> +  )
These two vals are effectively pointing to the same metric which ends up producing this warning when the application starts:

```
WARN  kamon.metric.MetricRegistry - Ignoring new description [Total number of connections across all target nodes] for metric [cassandra.client.pool.size]
```

The purpose of these two metrics is different so they should be kept as different metrics. Since the pool is actually more like a pool of pools we should make a better distinction between what is meant to track the behavior of the general pool and what is meant to track the behavior of the connection pool to a specific target (which, as far as I can understand will almost always be just 1 connection per target).

Based on the above, I would suggest to use:
  - `cassandra.client.pool.size` for the general pool size, meaning that it counts all connections regardless of the target.
  - `cassandra.client.pool.target.pool.size` (not sold on that name, open to suggestions) for the pools for each one of the targets. For this metric to actually be of value it should be possible to tag it with the target, otherwise it might not be very useful at all.

2019-12-18 08:27 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/PoolMetrics.scala
> +  )
These metrics have a similar situation as the above: we need to differentiate whether they belong to the general pool or the per-target pool, and the per-target values should be tagged with the target in order to be actually useful. This entire per-target tagging can be deadly because of how many time series it could generate. Would it be possible to keep the per-target stuff behind a config setting?

2019-12-18 08:27 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/QueryMetrics.scala
> +object QueryMetrics {
Please apply the same formatting as on PoolMetrics.

2019-12-18 08:27 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ConnectionPoolAdvices.scala
> +        metrics.inflightPerConnection.record(borrowedConnection.inFlight.get)
ping

2019-12-18 08:27 UTC, ivantopo commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/QueryMetrics.scala
> +    val cancelled: Counter              = CanceledExecutions.withoutTags()
These metrics should have the same tags as errors/timeouts. So far it seems like only `cassandra.dc` and `cassandra.cluster` will make it here. Doesn't say a lot but at least will keep all metrics consistent within the same instrument group.

2019-12-18 08:46 UTC, mladens commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/PoolMetrics.scala
> +  )
Leaving those two metrics there was a mistake, since both of them are measuring identical thing with or without the target dimension, i'd much prefer to keep one metric (albeit with a more generic description) and have 2 separate instances on the `PoolInstruments` object.

2019-12-18 08:51 UTC, mladens commented on kamon-cassandra-client/src/main/scala/kamon/instrumentation/cassandra/metrics/PoolMetrics.scala
> +  )
This is a similar situation only if we assume 1 connection per target host which is not neccessarily always true. Idea was to draw conclusions such as
- how saturated is the connection, should we increase pool size for (`connection.in-flight`)
- is there any disbalance in our query patterns, partitioning might be skewed (`target.in-flight`)

2019-12-18 09:05 UTC, mladens commented on kamon-cassandra-client/src/main/scala/com/datastax/driver/core/ConnectionPoolAdvices.scala
> +        metrics.inflightPerConnection.record(borrowedConnection.inFlight.get)
Not without a substantial revisit on the advices. This way its just exposing internal information contained within pool and connection. In order to move to range sampler we'd have to control both borrow and execution points (bring in both connection and pool info there), also make sure that we cover all exit-scenarios for a query so as not to leave sampler ever increasing. Not impossible, maybe not even hard but imho not worth it just so we can expose what is essentially same info. Please elaborate further if im missing some arguments there.

2020-01-27 15:55 UTC, dpsoft approved these changes
@mladens awesome!!

2020-02-16 08:02 UTC, dispalt commented
I'd love to use this, nice work.

2020-04-07 14:22 UTC, mladens commented
Kamon got moved to monorepo, closing this one, new PR here: https://github.com/kamon-io/Kamon/pull/763

2020-04-07 14:22 UTC, closed without merging